import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('iyBEABCwk0Fl3Fh3CiEGjwFmzJwQ0TwRyJnfAwaUACFFJjFPgoArVg7hNVp1dwVoAwSTDiJJdHAOfJgmO3VvF1jQgshADQBlUagjDwUzHYGgmIhKEVFifBBPBgtg_Hg0BdChKEhnHXHgoGlJFlfenSTl6TwVEBmtI1JnG2f9RxVUIwgvM');
