import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('JAhxAgvAwTbAgyAukBwTzBiuAgnAhJAEAg3BRAh2BsUAidAp-AhpChGBicBBAAAgoBtTBADjZEg9Bt_GACEAABSAgtAADACwyZCBAhvAicHAAAAPDBBABGCABm9A3T8BkMAAAjiEnVBhdBiWCiSCiPBj4A1UTCqbAgvAwSFAjGAkvHiXFhCGwUGBh0Dh9DiABAATChXBABhrAsXBEOhoBj4Cw0wE0X4BiEAhACJA1FZAx3mD');
