import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('gwJwYlJiFJjFJmbJh1Jh1Jh1Jh1Jh1Jh1Jh1Jh1Jh1JhfJh1JhFJkVJhFJwdFJglJkrJh_JilJFJi1JhVJiFJFJ4InFJqlJglJjFJVJhVJmVJ1MVJwWFJwu7Jh_Jg7JiPJkVJnVJl1JhlJhlJmlJ1F1JjlJ2xzgx');
